version: '3.3'
services:
  homepage:
    ports:
      - '3000:3000'
    volumes:
      - 'homepage_data:/app/config'
      - '/var/run/docker.sock:/var/run/docker.sock'
    image: 'ghcr.io/benphelps/homepage:latest'
volumes:
  homepage_data:
