version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - heimdall_data:/config
    ports:
      - 8210:80
    restart: unless-stopped

volumes:
  heimdall_data:
